name: Docker Base Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BASE: ghcr.io/lgisler/blue-whale/base
  XCBASE: ghcr.io/lgisler/blue-whale/xc-base-arm64

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Configure files
      run: ./configure

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into docker registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build base image and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.BASE }}
        cache-from: type=registry,ref=${{ env.BASE }}:buildcache
        cache-to: type=registry,ref=${{ env.BASE }}:buildcache,push=true
        context: native-compile/base

    - name: Build cross compile base image and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ env.XCBASE }}
        cache-from: type=registry,ref=${{ env.XCBASE }}:buildcache
        cache-to: type=registry,ref=${{ env.XCBASE }}:buildcache,push=true
        context: cross-compile/aarch64-linux-gnu/xc-base
